// Shared by the dashboard and its help assistant (no browser/server dependencies).
// Explicit action IDs are attached to controls. Never infer behaviour from
// words like "save", "cancel" or "upload": they mean different things per form.
export type DemoActionExplanation = {
  title: string;
  href: string;
  operator: string;
  result: string;
};

function action(href: string, title: string, operator: string, result: string): DemoActionExplanation {
  return { href, title, operator, result };
}

export const DEMO_HIDDEN_PATHS = ["/guide", "/customers", "/reviews", "/notifications", "/settings/ota", "/ota-drift", "/super-admin"];
export const DEMO_BOOKING_SITE_URL = "https://claires-hiking.booking.bookingtours.co.za";

export function isDemoPathVisible(href: string) {
  if (!href.startsWith("/") || href.startsWith("//")) return false;
  const path = href.split(/[?#]/)[0].replace(/\/+$/, "") || "/";
  return !DEMO_HIDDEN_PATHS.some((hidden) => path === hidden || path.startsWith(hidden + "/"));
}

export const DEMO_ACTIONS: Record<string, DemoActionExplanation> = {
  "dashboard.checkin": action("/", "Mark this booking as arrived", "Adds a check-in timestamp to this booking on the departure manifest.", "The team can see who has arrived. No payment or guest message is triggered."),
  "dashboard.uncheck": action("/", "Undo this guest check-in", "Clears the booking’s check-in flag and arrival timestamp.", "Use this to correct an accidental check-in. The reservation remains unchanged."),
  "weather.add": action("/", "Save a weather-monitoring location", "Adds the entered coordinates and optional Windguru spot to the dashboard’s locations.", "Your team can compare departure conditions; this does not change any meeting point sent to guests."),
  "weather.remove": action("/", "Remove this weather location", "Removes this saved location from the dashboard’s weather selector.", "It does not remove a tour, cancel a departure or change a guest booking."),
  "weather.default": action("/", "Set the default weather location", "Saves the selected location as the dashboard’s initial weather view.", "Staff start with the relevant forecast. Guest booking details are unaffected."),
  "billing.plan": action("/billing", "Switch the operator subscription plan", "Changes to the selected plan, adjusts included seats and prorates the current billing period.", "This changes your platform subscription, not the price guests pay for a tour."),
  "booking.cancel": action("/bookings", "Cancel this booking", "Cancels this party only and releases its places.", "Paid guests may choose rebooking, credit or refund. Late cancellations need an explicit override to offer those choices."),
  "booking.weather": action("/bookings", "Weather-cancel this departure", "Closes this departure and cancels every active booking on it.", "Email and WhatsApp explain the cancellation. Eligible paid guests choose rebooking, a voucher or a full refund; unpaid guests get a notice."),
  "booking.paid": action("/bookings", "Record an EFT or cash payment", "Records money you have already received outside online checkout.", "The booking becomes paid and confirmation is sent. This button does not collect money."),
  "booking.payment": action("/bookings", "Send a booking payment link", "Creates checkout for the amount still due and sends the link to the booker.", "The guest pays against this booking, without entering their trip details again."),
  "booking.reminder": action("/bookings", "Remind a guest to pay", "Sends a payment-outstanding reminder using the booking’s existing checkout link.", "The guest can finish paying for their reserved places."),
  "booking.reschedule-link": action("/bookings", "Collect the reschedule difference", "Sends a fresh payment link for the extra cost of the proposed move.", "Email and WhatsApp let the guest pay the difference to complete the reschedule."),
  "booking.invoice": action("/invoices", "Resend the booking invoice", "Sends the latest invoice for this paid booking to the booker.", "The guest receives a copy for their records, not a new payment request."),
  "booking.allow-unpaid": action("/bookings", "Allow this booking without payment", "Keeps this reservation valid while unpaid; disables its payment reminders and automatic cancellation.", "Useful for an agreed pay-on-arrival arrangement. No payment is recorded."),
  "booking.require-payment": action("/bookings", "Require payment for this booking", "Restores payment reminders and automatic cancellation for this unpaid reservation.", "The guest must pay by the applicable deadline to keep the booking."),
  "booking.checkin": action("/bookings", "Check in selected guests", "Marks the selected bookings as arrived on the manifest.", "Your team can see who is present. No message or charge is triggered."),
  "booking.edit": action("/bookings", "Save booking details", "Updates this booking’s editable guest and reservation fields.", "The manifest uses the corrected information and the guest is notified of the update."),
  "booking.contact": action("/bookings", "Correct this booker’s contact details", "Saves the lead booker’s name, phone number and email address.", "An update email is attempted; future booking communication uses the corrected details."),
  "booking.rebook": action("/bookings", "Move this party to another departure", "Checks the new departure’s capacity and adjusts the booking and places.", "Any extra cost is collected through a difference-payment link before a paid upgrade completes."),
  "booking.refund": action("/refunds", "Refund and cancel this booking", "Cancels the booking and requests the entered refund against its recorded payment.", "Card refunds go through Yoco; voucher credit follows the voucher flow. A request is not proof the money has arrived."),
  "booking.whatsapp": action("/inbox", "Send a WhatsApp greeting", "Sends your opening message to this booker, then opens their inbox conversation.", "The guest replies in the same WhatsApp thread."),
  "booking.reduce": action("/bookings", "Reduce the party size", "Releases the removed guests’ places and applies your chosen refund or credit option.", "The guest is notified. Reductions are blocked within 24 hours of departure."),
  "booking.code": action("/bookings", "Apply a voucher or promo code", "Validates the code against this booking and applies eligible credit or discount.", "The remaining amount due is recalculated before payment."),
  "booking.export": action("/bookings", "Export the filtered manifest", "Downloads the displayed booking range as CSV, with special requests masked.", "Your team gets a working guest list without exposing sensitive request text."),
  "booking.export-sensitive": action("/bookings", "Export the full manifest", "Downloads the filtered bookings including unmasked special requests.", "The file can contain sensitive guest information. Share it only with authorised staff."),
  "booking.create": action("/new-booking", "Create a phone or walk-in booking", "Reserves places on the chosen departure with the guest, extras and payment method you entered.", "Offline sales join the same manifest and capacity pool as website and WhatsApp bookings."),
  "slot.save": action("/slots", "Update this departure", "Changes its time, capacity or price override. A time change can also move matching future departures.", "Availability uses the new values. Saving alone does not cancel existing bookings."),
  "slot.close": action("/slots", "Close sales for this departure", "Stops new bookings for this slot, without cancelling existing guests.", "Booked guests keep their reservations. No cancellation notice or refund is sent."),
  "slot.reopen": action("/slots", "Reopen this departure", "Makes the closed slot available for new bookings again.", "Previously cancelled bookings are not restored automatically."),
  "slot.cancel": action("/slots", "Cancel this departure and notify guests", "Closes the slot and cancels all its active bookings with your operational reason.", "Guests receive email and WhatsApp notices; eligible paid guests choose how to recover their booking value."),
  "slot.weather": action("/slots", "Weather-cancel this departure", "Closes the slot and cancels all its active bookings because of weather.", "Eligible paid guests get rebooking, voucher or full-refund choices, even at short notice."),
  "slot.cancel-days": action("/slots", "Weather-cancel selected days", "Closes departures across the dates you selected and cancels their active bookings.", "Affected bookers receive notices and applicable recovery options, without cancelling each booking by hand."),
  "slot.reopen-days": action("/slots", "Reopen departures on selected days", "Reopens closed slots on the selected dates for new sales.", "Cancelled guests stay cancelled; reopening does not recreate their bookings."),
  "slot.create": action("/slots", "Create departures across date ranges", "Adds the chosen tour, departure time, capacity and optional price across your selected dates.", "The new slots become available to book through connected direct-booking channels."),
  "slot.generate": action("/slots", "Generate a recurring departure schedule", "Creates slots for the tour, date range, times and weekdays you choose.", "Build a season’s availability without entering each departure separately."),
  "slot.bulk": action("/slots", "Bulk-update departures", "Applies the entered time, capacity or price to slots matching the tour and dates.", "Blank fields stay unchanged; existing guest bookings are not cancelled by this edit."),
  "slot.capacity": action("/settings#tours", "Update capacity for this departure time", "Changes capacity across the selected bundle of future slots at this time.", "The calendar and booking flow use the revised number of places."),
  "slot.delete-open": action("/settings#tours", "Delete empty departures at this time", "Removes future slots from this time bundle only when they have no bookings or holds.", "The removed departures can no longer be selected for new bookings."),
  "refund.process": action("/refunds", "Submit a card refund", "Requests the approved refundable amount through Yoco against a recorded card payment.", "The refund remains pending until the payment provider confirms its outcome."),
  "refund.check": action("/refunds", "Check a pending card refund", "Checks the provider’s result for an already-submitted refund.", "Updates its recorded status; this is not a second refund request."),
  "refund.manual": action("/refunds", "Confirm a bank refund you made", "Records that you have already refunded the guest by bank transfer.", "This does not move money from your bank account. Transfer it before confirming."),
  "refund.decline": action("/refunds", "Decline this refund request", "Marks an eligible requested or failed refund as declined.", "The booker is emailed the decision when an email is available. No money is returned."),
  "refund.all": action("/refunds", "Process eligible card refunds", "Attempts the queued card refunds in a batch and records each result.", "Bank-transfer refunds still need manual handling; a failed request is not marked paid."),
  "invoice.download": action("/invoices", "Download this invoice", "Downloads the selected booking invoice for your records.", "No email is sent and the booking’s payment status is unchanged."),
  "invoice.print": action("/invoices", "Print or save this invoice as PDF", "Opens a print-ready invoice with the booking and company details.", "You can print it or save a PDF without sending a new invoice email."),
  "voucher.create": action("/vouchers", "Sell a gift voucher by payment link", "Creates the voucher order and emails the buyer a checkout link.", "The gift becomes usable after payment; creating the order is not free voucher credit."),
  "pricing.save": action("/pricing", "Save each tour’s standard and peak prices", "Stores the tour prices used by normal and peak-priced departures.", "Pricing stays tied to the tour rather than requiring a separate edit for every slot."),
  "pricing.apply": action("/pricing", "Apply peak pricing to a date range", "Marks the selected period for peak pricing on the chosen tours.", "Guests see the applicable seasonal price when they choose a departure."),
  "pricing.remove": action("/pricing", "Remove this peak-price period", "Removes the peak rule for this date range.", "Affected slots return to their normal pricing rules, subject to other overrides."),
  "inbox.reply": action("/inbox", "Reply to this guest", "Sends your typed reply through this conversation’s WhatsApp or web-chat channel.", "The guest hears from your team in the conversation they already started."),
  "inbox.bot": action("/inbox", "Hand this conversation back to the bot", "Releases the human takeover so the assistant can handle new messages.", "The guest stays in the same thread; bot replies still follow your configured mode."),
  "inbox.end": action("/inbox", "End this guest chat", "Ends the active human-handled chat session.", "This is a conversation action. It does not cancel the guest’s booking."),
  "broadcast.send": action("/broadcasts", "Message guests on selected departures", "Sends your notice to bookers on the selected slots by email and WhatsApp where possible.", "Useful for meeting-point or timing updates. Sending a notice does not cancel bookings."),
  "broadcast.weather": action("/broadcasts", "Weather-cancel the selected departures", "Closes the selected slots, cancels their bookings and records the cancellation broadcast.", "Affected guests get notices and eligible paid guests get recovery choices; empty slots are simply closed."),
  "photo.upload": action("/photos", "Upload departure photos to Google Drive", "Uploads your selected files into the connected Drive storage for this departure.", "Uploading prepares the photos; use Send Photos to share them with bookers."),
  "photo.send": action("/photos", "Send photo links to lead bookers", "Emails and WhatsApps the supplied photo links to lead bookers on the selected departure.", "Everyone receives the right trip’s photos without you messaging each party separately."),
  "photo.links": action("/photos", "Import photo links", "Adds pasted photo URLs to this departure’s sharing list.", "Links are prepared for review, not sent until you choose Send Photos."),
  "campaign.cancel": action("/marketing", "Cancel the scheduled campaign", "Stops this campaign before its scheduled send.", "No campaign email is sent to the remaining audience."),
  "campaign.pause": action("/marketing", "Stop the campaign’s remaining sends", "Cancels further delivery for this campaign.", "Emails already delivered cannot be recalled."),
  "template.save": action("/marketing/templates", "Save this reusable email template", "Stores the subject, content blocks, images and styling in your template library.", "Reuse the design in campaigns or automated journeys. Saving does not email anyone."),
  "template.duplicate": action("/marketing/templates", "Duplicate this email template", "Creates a separate editable copy of the selected design.", "The original stays available for campaigns and automations already using it."),
  "template.delete": action("/marketing/templates", "Delete this email template", "Removes the selected reusable design from the library.", "Review linked campaigns or automation steps before removing a template they need."),
  "template.test": action("/marketing/templates", "Send a test email", "Sends this template to the configured admin test recipient.", "Check layout and links in an inbox before sending to customers."),
  "template.send": action("/marketing/templates", "Send this email campaign", "Creates and sends the named campaign to the selected eligible marketing audience.", "Active, consented contacts receive the email; tag filters narrow the audience."),
  "template.schedule": action("/marketing/templates", "Schedule this email campaign", "Queues the campaign for the date and time you selected.", "The eligible audience receives it when the scheduled dispatch runs."),
  "template.image": action("/marketing/templates", "Upload an email image", "Uploads an image for the email design you are editing.", "The image belongs to the template, not a guest trip-photo delivery."),
  "automation.create": action("/marketing/automations", "Create a draft automation", "Adds a customer journey with a trigger and editable steps.", "No customer messages run until you configure and activate it."),
  "automation.template": action("/marketing/automations", "Create a journey from this template", "Copies the selected workflow’s trigger and steps into an editable draft.", "Review the timing, audience and linked emails before activating the journey."),
  "automation.save": action("/marketing/automations", "Save this customer journey", "Stores the trigger, conditions and ordered email, wait, tag or promo steps.", "Booking events and contact data can drive follow-ups without a separate mailing list workflow."),
  "automation.activate": action("/marketing/automations", "Activate this automation", "Checks the workflow and enables its trigger and scheduled steps.", "Matching contacts can enter the journey and receive its configured messages."),
  "automation.pause": action("/marketing/automations", "Pause this automation", "Stops this workflow from dispatching further steps while paused.", "Previously sent emails remain delivered; the workflow stays available to edit."),
  "automation.archive": action("/marketing/automations", "Archive this automation", "Takes the workflow out of the active list while preserving its history.", "Past journey activity remains available for reference."),
  "automation.restore": action("/marketing/automations", "Restore the automation as a draft", "Returns the archived workflow to the working list in draft status.", "Restoring it does not restart customer messages automatically."),
  "automation.delete": action("/marketing/automations", "Delete this automation permanently", "Removes this workflow rather than keeping it in the archive.", "Use archive when you need to retain the journey’s history."),
  "automation.test": action("/marketing/automations", "Email yourself every linked step", "Sends the workflow’s linked email templates to the admin test inbox.", "Review the complete email sequence without enrolling customers."),
  "automation.dispatch": action("/marketing/automations", "Run due automation steps now", "Runs the dispatch worker for eligible, due journey steps.", "This can send real emails in a live account; it is not a preview button."),
  "automation.enroll": action("/marketing/automations", "Enrol this contact in the journey", "Adds the selected contact to this automation, subject to eligibility checks.", "The contact follows the journey’s timing and configured steps."),
  "contact.add": action("/marketing/contacts", "Add a marketing contact", "Adds the entered contact details, consent choice and tags to your audience.", "Marketing eligibility depends on consent and status, not simply having an email address."),
  "contact.save": action("/marketing/contacts", "Save this marketing contact", "Updates the selected audience record’s editable details.", "Campaign targeting uses the corrected contact information."),
  "contact.activate": action("/marketing/contacts", "Activate this marketing contact", "Changes this contact’s status to active.", "Only reactivate with appropriate consent; changing status does not supply missing marketing consent."),
  "contact.unsubscribe": action("/marketing/contacts", "Unsubscribe this marketing contact", "Changes this contact’s status to unsubscribed.", "The contact leaves the sending audience, while their record and booking history remain."),
  "contact.tag": action("/marketing/contacts", "Update this contact’s tags", "Adds or removes a segment label on this audience record.", "Tag-based campaigns and journey conditions use these labels."),
  "contact.delete": action("/marketing/contacts", "Delete this marketing contact", "Removes this contact from the marketing audience.", "This is not a POPIA erasure of the guest’s bookings or financial records."),
  "contact.delete-all": action("/marketing/contacts", "Delete the marketing audience", "Removes all marketing contact records after explicit confirmation.", "This is a bulk audience removal, not a booking cancellation or customer-data erasure."),
  "contact.import": action("/marketing/contacts", "Import a mapped contact list", "Imports valid CSV rows after column mapping and preview.", "Imported contacts retain their consent and status rules before they can receive marketing."),
  "contact.validate": action("/marketing/contacts", "Validate and segment the audience", "Checks contact email data and applies the selected validation and segmentation rules.", "Review the resulting status and tags before using the list for a campaign."),
  "contact.clean": action("/marketing/contacts", "Deactivate stale marketing contacts", "Marks the previewed stale contacts inactive instead of deleting their records.", "They leave the active sending audience while their records remain available."),
  "promo.save": action("/marketing/promotions", "Save this promo code", "Stores its discount, validity dates, use limits and eligible tours.", "Eligible guests can apply it at checkout; limits are checked when it is used."),
  "promo.activate": action("/marketing/promotions", "Activate this promo code", "Enables the code for new redemptions within its validity and usage limits.", "An expired or exhausted code still cannot be used until those limits are changed."),
  "promo.deactivate": action("/marketing/promotions", "Deactivate this promo code", "Stops accepting this code on new bookings.", "Previously discounted bookings keep their recorded totals."),
  "promo.delete": action("/marketing/promotions", "Delete this promo code", "Removes this promotion from the available code list.", "Guests cannot use the removed code on a new booking."),
  "partner.invite": action("/partnerships", "Invite an operator to partner", "Sends a partnership invitation to the operator email you entered.", "Accepted partners can build shared combo offers with agreed revenue shares."),
  "partner.accept": action("/partnerships", "Accept this operator partnership", "Activates the invitation between your business and this partner.", "The partnership can be used for joint combo offers; accepting does not publish one."),
  "partner.revoke": action("/partnerships", "Revoke this partnership", "Ends the active relationship for future partnership operations.", "Review joint offers and outstanding settlements; revoking does not pay a partner."),
  "partner.offer": action("/partnerships", "Create a multi-tour combo offer", "Bundles your own or partner tours with a total price and per-tour revenue shares.", "Guests can buy a combined experience while operator shares are tracked together."),
  "partner.activate": action("/partnerships", "Activate this combo offer", "Enables this multi-tour offer for new combo bookings.", "Guests can book it when the linked tours and departure choices are available."),
  "partner.deactivate": action("/partnerships", "Deactivate this combo offer", "Stops selling this bundle on new combo bookings.", "Existing combo sales and partner-settlement records remain."),
  "partner.rules": action("/partnerships", "Save combo booking rules", "Stores the offer’s booking constraints and allowed combinations.", "The combo booking flow checks those rules when guests select their experiences."),
  "partner.link": action("/partnerships", "Collect a partner settlement", "Creates a payment link for the partner’s outstanding share owed to your business.", "This settles money between operators; it is not a guest booking-payment link."),
  "partner.settle": action("/partnerships", "Record a completed partner settlement", "Marks the listed unsettled combo items as settled after payment outside this flow.", "No money moves when you press this button."),
  "billing.add": action("/billing", "Add a paid admin seat", "Increases the number of purchased dashboard seats.", "The extra seat changes subscription billing; it does not invite a staff member by itself."),
  "billing.remove": action("/billing", "Remove an unused admin seat", "Reduces purchased seats when your current users fit within the lower limit.", "Subscription seat charges adjust; existing user accounts are not deleted."),
  "billing.pause": action("/billing", "Pause for the off-season", "Pauses subscription billing, new bookings, marketing and broadcasts.", "Your team can still sign in and view records. Resume when the season starts again."),
  "billing.resume": action("/billing", "Resume the operator subscription", "Reactivates the paused subscription and its normal billing.", "Your business can accept new bookings again when the account is active."),
  "report.csv": action("/reports", "Export the filtered booking report", "Downloads the current report’s booking data as a CSV spreadsheet.", "The date and tour filters determine the export; nothing is sent to guests."),
  "report.pdf": action("/reports", "Download the report as PDF", "Creates a printable report for the current filters.", "Use it for an internal review or accountant handover without changing bookings."),
  "report.refunds": action("/reports", "Export the refund register", "Downloads refund records for the reporting period.", "Reconcile returned amounts separately from sales and amounts still owed."),
  "report.invoices": action("/reports", "Export the invoice register", "Downloads the period’s invoice records as CSV.", "Your accountant gets invoice-level data, not the guest manifest."),
  "report.vouchers": action("/reports", "Export the voucher register", "Downloads voucher records and their financial balances.", "Track gift credit separately from cash sales and redeemed booking value."),
  "report.settlements": action("/reports", "Export combo settlements", "Downloads partner settlement records for the reporting period.", "Reconcile the shares owed between operators separately from guest payments."),
  "privacy.export": action("/privacy/data-requests", "Export the requester’s personal data", "Builds the export for this verified access request and emails the customer a download link.", "The file contains that requester’s personal information; it is not a whole-business export."),
  "privacy.fulfill": action("/privacy/data-requests", "Fulfil this confirmed deletion request", "Permanently anonymises this customer’s personal data after confirmation.", "Financial records remain with anonymised identifiers. This cannot be undone."),
  "privacy.reject": action("/privacy/data-requests", "Reject this privacy request with a reason", "Records your reason for declining the request and notifies the customer.", "The request is closed as rejected, not marked fulfilled or erased."),
};

export function getDemoActionExplanation(id: string, subject?: string) {
  const feature = DEMO_ACTIONS[id] ?? DEMO_SETTINGS[id] ?? null;
  return feature && subject ? { ...feature, title: `${feature.title}: ${subject}` } : feature;
}

const setting = (section: string, title: string, operator: string, result: string) => action(`/settings#${section}`, title, operator, result);

export const DEMO_SETTINGS: Record<string, DemoActionExplanation> = {
  admins: setting("admins", "Staff access and account ownership", "Invite staff and control which settings and dashboard sections each admin can use.", "Give the team the tools they need while keeping credentials and billing with the main admin."),
  "admin.add": setting("admins", "Invite a dashboard admin", "Creates the staff account and emails a secure password-setup link.", "The new admin sets their own password. Seat availability is checked before the account is added."),
  "admin.remove": setting("admins", "Remove this admin’s access", "Removes the selected admin account, subject to account-ownership protections.", "This changes staff access, not guest bookings or customer records."),
  "admin.promote": setting("admins", "Make this user a main admin", "Grants full operator settings and staff-management access.", "Main-admin access includes sensitive integration and account controls; grant it only to trusted owners."),
  "admin.demote": setting("admins", "Change this user to an admin", "Removes main-admin privileges and uses the user’s assigned section permissions.", "Account-ownership protections prevent removing the required main-admin access."),
  "admin.setup": setting("admins", "Resend a password-setup link", "Emails this invited admin a fresh link to finish setting up their password.", "It does not reveal or choose a password for them."),
  "admin.reset": setting("admins", "Email this admin a password-reset link", "Sends the selected staff member a secure password-reset email.", "They choose the replacement password themselves."),
  "admin.grant": setting("admins", "Grant settings access", "Allows this admin to open and manage this configuration section.", "Access is per person; integration credentials remain main-admin-only."),
  "admin.revoke": setting("admins", "Remove settings access", "Removes this admin’s permission to manage this configuration section.", "Other granted sections stay available to them."),
  "admin.show": setting("admins", "Show this dashboard area", "Makes this area visible to this staff member.", "This changes their dashboard, not the public booking site."),
  "admin.hide": setting("admins", "Hide this dashboard area", "Removes this area from this staff member’s dashboard access.", "Other admins keep their own visibility settings."),
  "admin.billing": setting("admins", "Choose the subscription billing contact", "Selects which admin receives BookingTours subscription invoices.", "This does not change the recipient of guest booking invoices."),
  "admin.test-email": setting("admins", "Choose the marketing test recipient", "Directs test template and workflow emails to the selected admin.", "Preview campaigns in an internal inbox before sending them to the guest audience."),
  "admin.suspend": setting("admins", "Suspend the operator subscription", "Suspends normal operator access and new-booking operations.", "Reports, invoices, refunds and settings remain accessible for account administration."),
  "admin.reactivate": setting("admins", "Reactivate the operator subscription", "Returns the suspended subscription to active operation.", "Normal operator access and new-booking operations become available again."),
  "logo.upload": setting("admins", "Set your business logo", "Uploads the logo used in the dashboard, booking site, customer emails and invoices.", "One brand image carries through the direct booking journey. It does not send trip photos."),
  "logo.remove": setting("admins", "Remove the business logo", "Clears the shared logo from your business branding.", "The booking site, emails and invoices use their fallback branding instead."),
  tours: setting("tours", "Tours, capacity and last-minute deals", "Set activity descriptions, prices, duration and departure schedules in one place.", "Timed last-minute prices can help sell remaining places; custom checkout questions capture trip-specific needs."),
  "tour.save": setting("tours", "Save this tour’s booking details", "Stores its description, price, duration, capacity defaults and last-minute deal settings.", "The same tour powers direct bookings and the departure schedule; the confirmation tagline personalises its emails."),
  "tour.activate": setting("tours", "Activate this tour", "Makes the tour active for booking, subject to its visibility and available slots.", "Guests can choose it when bookable departures are available."),
  "tour.deactivate": setting("tours", "Deactivate this tour", "Takes the activity out of active sale without deleting its record.", "Use this when an experience is temporarily unavailable; it does not cancel existing bookings."),
  "tour.show": setting("tours", "Show this tour on the booking site", "Removes the tour’s hidden flag.", "An active tour with available departures can appear in the public tour list."),
  "tour.hide": setting("tours", "Hide this tour from the public list", "Hides the tour card without deactivating the activity.", "Keep a tour out of the general storefront while retaining it for operational use."),
  "tour.delete": setting("tours", "Delete this unbooked tour", "Removes the activity only if it has no booking history or linked active vouchers.", "These protections prevent deleting the tour behind a guest’s booking or usable gift credit."),
  "tour.image": setting("tours", "Upload a tour-card image", "Adds a photo to this tour’s booking-page card.", "Guests see the activity image while choosing a tour; no photo message is sent."),
  "tour.image-remove": setting("tours", "Remove this tour-card image", "Clears the image from the tour form; save the tour to publish the change.", "This only affects the activity card, not photos from completed trips."),
  "tour.reorder": setting("tours", "Reorder the public tour list", "Saves the order in which tours appear on the booking site.", "Put a signature or seasonal experience first without changing its price or availability."),
  "tour.last-minute": setting("tours", "Time-limited last-minute pricing", "Set a deal price and the hours before departure when it starts and ends.", "Upcoming departures follow the deal window automatically, helping sell late availability without daily price edits."),
  "questions.save": setting("tours", "Save custom checkout questions", "Publishes your questions, answer types and required fields to checkout.", "Collect needs such as allergies or equipment sizes with the booking, instead of chasing guests afterwards."),
  addons: setting("addons", "Sell optional extras at checkout", "Create priced add-ons such as equipment hire or a photo package.", "Guests select extras alongside the tour; their booking records the chosen items and cost."),
  "addon.save": setting("addons", "Save this booking add-on", "Stores the extra’s name, description, image, price and active status.", "Active extras can be offered alongside the tour at checkout."),
  "addon.activate": setting("addons", "Activate this checkout extra", "Makes the add-on available for new bookings.", "Guests can select it and see its additional price during checkout."),
  "addon.deactivate": setting("addons", "Deactivate this checkout extra", "Stops offering the extra on new bookings without deleting its definition.", "Previously booked extras keep their recorded booking details."),
  "addon.delete": setting("addons", "Delete this add-on", "Removes the selected extra from the add-on catalogue.", "It is no longer offered for new purchases."),
  "addon.image": setting("addons", "Upload an add-on image", "Adds an illustration or photo to this optional checkout extra.", "Guests can see what the extra includes before buying it."),
  "addon.image-remove": setting("addons", "Remove this add-on image", "Clears the extra’s image in the form; save the add-on to publish it.", "The add-on can still be sold using its name, description and price."),
  "addon.reorder": setting("addons", "Reorder checkout extras", "Saves the display order of the add-ons.", "Feature the most useful extras first without changing their prices."),
  external: setting("external", "Connect a direct booking partner", "Create partner API credentials and map their product codes to your tours.", "Approved partners can submit bookings against your availability through the B2B integration."),
  "external.save-key": setting("external", "Save a partner API credential", "Creates or updates the selected partner’s authentication details.", "This credential authorises the partner integration; it is not a guest checkout key."),
  "external.enable-key": setting("external", "Enable this partner API credential", "Allows the partner to authenticate requests with this credential.", "Product mappings still determine which tours incoming bookings can use."),
  "external.disable-key": setting("external", "Disable this partner API credential", "Stops this credential from authenticating new requests.", "Existing bookings stay recorded; the credential can be enabled again later."),
  "external.delete-key": setting("external", "Delete this partner API credential", "Removes the selected credential from the integration.", "The partner needs a valid replacement before using the API again."),
  "external.save-map": setting("external", "Map a partner product to a tour", "Links the external product identifier to the selected BookingTours activity.", "Incoming partner bookings are routed to the correct tour and departure availability."),
  "external.enable-map": setting("external", "Enable this partner product mapping", "Activates the link between this external product and your tour.", "Authenticated partner bookings can use this mapping to find the correct activity."),
  "external.disable-map": setting("external", "Disable this partner product mapping", "Stops using this external product link for new partner bookings.", "The mapping stays saved so you can re-enable it without entering the details again."),
  "external.delete-map": setting("external", "Delete this partner product mapping", "Removes the link between this external product and your tour.", "The partner product must be mapped again before bookings can route through it."),
  "external.copy": setting("external", "Copy this partner integration value", "Copies the displayed API instruction, identifier or credential for partner setup.", "Treat credentials as secrets and share them only with the intended integration partner."),
  site: setting("site", "Your own branded booking site", "Control the public page’s wording, images, colours, policies, contact details and booking links.", "The live preview uses the booking site’s theme engine, including automatic text-contrast adjustment."),
  "site.save": setting("site", "Publish the booking-site settings", "Saves the site’s branding, copy, policies, colours, links and chatbot avatar.", "Guests book on your branded page, with your contact details and your instructions."),
  "site.hero": setting("site", "Upload the booking-page background", "Replaces the hero background on your public booking page.", "The image brands the storefront; it is not added to any guest photo delivery."),
  "site.hero-remove": setting("site", "Remove the booking-page background", "Clears the custom hero image from the public page.", "The page returns to its theme background; tours and availability stay unchanged."),
  "site.avatar": setting("site", "Choose your guest chatbot’s avatar", "Sets the illustrated face shown by the booking-site chat widget.", "It changes the assistant’s appearance, not its booking logic or knowledge."),
  "site.cancellation": setting("site", "Save time-based cancellation tiers", "Sets refund percentages according to how many hours remain before departure.", "Customer cancellations use these tiers; operator weather cancellations have their separate recovery flow."),
  "embed-widget": setting("embed-widget", "Embed booking on your existing website", "Provides a tenant-specific snippet for your current website.", "Guests use your tours and live availability without you rebuilding the booking flow."),
  "embed.copy": setting("embed-widget", "Copy your booking-widget snippet", "Copies the code containing your business’s tenant identifier.", "Your website editor can paste it into the existing site to load your booking widget."),
  email: setting("email", "Brand every transactional email", "Choose a shared email colour, per-message banner images, activity wording and social links.", "Confirmations, invoices, cancellations and photo emails stay recognisably yours, not generic platform messages."),
  "email.save": setting("email", "Save customer-email branding", "Stores the email theme, message-specific images, wording and social links.", "Future transactional emails use these settings; saving does not send an email."),
  "email.image": setting("email", "Upload a transactional-email banner", "Uploads the banner for the email type named beside this control.", "Only that message type uses the image; it is not a trip-photo broadcast."),
  operations: setting("operations", "Teach the guest assistant about your business", "Set what to bring and wear, arrival instructions, FAQs and the chatbot’s tone and business knowledge.", "The website and WhatsApp assistant use your information; arrival and packing details also feed guest emails."),
  "operations.save": setting("operations", "Save operations and AI knowledge", "Stores the guest instructions, FAQ answers and AI personality prompt.", "Keep automated answers and pre-trip communication aligned with how your business actually operates."),
  "whatsapp-bot": setting("whatsapp-bot", "Choose when WhatsApp answers automatically", "Run the bot always, only outside configured support hours, or never.", "Your team can handle chats during working hours while the assistant covers the gaps in your business timezone."),
  "whatsapp.save": setting("whatsapp-bot", "Save WhatsApp reply hours and mode", "Stores the auto-reply mode and weekly opening and closing times.", "Outside-hours mode uses that schedule; an individual chat’s human takeover still controls who replies."),
  "dashboard-prefs": setting("dashboard-prefs", "Your personal dashboard assistant", "Show or hide the floating dashboard help bubble for your own admin account.", "This preference follows your account, not the whole team. It does not disable the guest chatbot."),
  "assistant.toggle": setting("dashboard-prefs", "Show or hide your help bubble", "Saves your personal preference for the dashboard help assistant.", "Other admins keep their own preference; the demo assistant remains available for this tour."),
  autotags: setting("autotags", "Turn booking activity into marketing segments", "Set rules for VIP, lapsed, new-booker, completed-tour and expiring-voucher tags.", "Booking activity can keep the marketing audience up to date without manually maintaining a second list."),
  "tags.save": setting("autotags", "Save automatic contact-tag rules", "Stores VIP thresholds, inactivity periods and enabled booking-behaviour tags.", "Automatic tagging uses these rules for audience segmentation and tag-based journeys."),
  invoice: setting("invoice", "Your company and bank details on invoices", "Set the legal name, registration, VAT number, address and EFT banking information.", "Guest pro forma invoices carry your business details; this is separate from BookingTours subscription billing."),
  "invoice.settings": setting("invoice", "Save invoice and EFT details", "Stores the company and permitted banking fields used on guest invoices.", "Guests receive the correct billing identity and bank-transfer instructions on future invoices."),
  credentials: setting("credentials", "Connect payments, messaging and photo storage", "Main admins manage WhatsApp, Yoco and Google Drive independently.", "Secrets are encrypted at rest. Updating one integration does not replace the credentials for another."),
  "credentials.whatsapp": setting("credentials", "Save WhatsApp business credentials", "Stores the Meta access token and phone-number ID for your business.", "These identify the WhatsApp number used for automated guest messages and inbox replies."),
  "credentials.yoco": setting("credentials", "Save live Yoco payment credentials", "Stores the live secret key and webhook-signing secret for your Yoco account.", "Checkout collects card payments; verified payment events update booking status."),
  "credentials.yoco-test": setting("credentials", "Save Yoco sandbox credentials", "Stores separate test keys for trying the payment flow without live charges.", "Live payment keys remain separate; test mode must be selected to use the sandbox."),
  "credentials.test-on": setting("credentials", "Switch Yoco to sandbox payments", "Routes supported checkout flows through the saved Yoco test credentials.", "Test payments do not charge real cards. Switch back before taking live bookings."),
  "credentials.test-off": setting("credentials", "Switch Yoco back to live payments", "Turns off sandbox routing so checkout uses the live Yoco credentials.", "Payments in a live account can charge real cards once live credentials are configured."),
  "credentials.drive": setting("credentials", "Connect Google Drive for trip photos", "Starts Google’s permission flow to connect photo storage for your business.", "Staff can upload departure photos, then share their links with the right bookers."),
  "credentials.drive-off": setting("credentials", "Disconnect Google Drive", "Removes the stored Drive connection for future uploads.", "This does not delete photos already stored in your Google Drive."),
  "faq.save": action("/settings/chat-faq", "Save an exact chatbot quick answer", "Stores the question pattern, keywords, intent and answer for this FAQ rule.", "Matching guest questions can use your approved reply instead of relying only on an AI-generated answer."),
  "faq.on": action("/settings/chat-faq", "Enable this quick answer", "Makes this saved rule available to the guest chatbot.", "Matching questions can receive the answer you wrote."),
  "faq.off": action("/settings/chat-faq", "Disable this quick answer", "Stops using this rule without deleting its saved wording.", "Other FAQ rules and the assistant’s general knowledge remain available."),
  "faq.delete": action("/settings/chat-faq", "Delete this quick answer", "Removes the selected question-matching rule and its saved reply.", "The chatbot can no longer select this specific answer."),
};

// These two booking-menu components share exact labels on desktop and mobile.
export function bookingDemoAction(label: string) {
  return ({
    "Mark Paid": "booking.paid", "Pay Link": "booking.payment", "Payment Link": "booking.payment",
    "Payment Reminder": "booking.reminder", "Allow Without Payment": "booking.allow-unpaid",
    "Require Payment": "booking.require-payment", "Cancel": "booking.cancel",
    "Resend Invoice": "booking.invoice", "Resend Inv": "booking.invoice",
  } as Record<string, string>)[label];
}
