// IMPORTANT: This function uses the service role key, which BYPASSES RLS.
// Every query against a tenant-owned table MUST include .eq("business_id", X).
//
// Fix 4: the enforcement linkage between an unpaid platform invoice and whether
// the tenant may keep trading. Before this existed, the only consequence of not
// paying BookingTours was a human noticing.
//
// Deliberately NOT a billing engine: invoices are still generated by hand, no
// cards are stored, nothing is auto-debited. All this does is move
// businesses.subscription_status when an issued invoice goes unpaid, and move
// it back when the money lands (see _shared/billing.ts).
//
// Timeline, from the invoice's sent_at:
//   + BILLING_GRACE_DAYS   (default 7)  -> PAST_DUE  + one reminder email
//   + BILLING_SUSPEND_DAYS (default 21) -> SUSPENDED + tenant and platform notified
//
// PAST_DUE is a warning, not a lockout: the tenant keeps trading, the storefront
// keeps selling, AuthGate shows a banner. Only SUSPENDED stops trade.
//
// Idempotent by construction: every transition is guarded on the tenant's
// current status, so a second run on the same day sees the new state and does
// nothing. Re-running never re-sends an email or re-writes an audit row.
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createServiceClient } from "../_shared/tenant.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const ENFORCEMENT_KEY = Deno.env.get("BILLING_ENFORCEMENT_KEY") || "";
const GRACE_DAYS = Number(Deno.env.get("BILLING_GRACE_DAYS") || "7");
const SUSPEND_DAYS = Number(Deno.env.get("BILLING_SUSPEND_DAYS") || "21");
const PLATFORM_ALERT_EMAIL = Deno.env.get("PLATFORM_BILLING_ALERT_EMAIL") || "";

const supabase = createServiceClient();

const JSON_HEADERS = { "Content-Type": "application/json" };

// Mirrors app/api/platform-invoices/send/route.ts: billing reaches ONE person,
// the operator's chosen billing contact, else the oldest admin on the business.
async function billingContact(businessId: string, billingAdminUserId: string | null) {
  if (billingAdminUserId) {
    const { data } = await supabase.from("admin_users")
      .select("email, name").eq("id", billingAdminUserId).eq("business_id", businessId).maybeSingle();
    if (data?.email) return data as { email: string; name: string };
  }
  const { data } = await supabase.from("admin_users")
    .select("email, name").eq("business_id", businessId)
    .order("created_at", { ascending: true }).limit(1).maybeSingle();
  return data?.email ? (data as { email: string; name: string }) : null;
}

async function sendEmail(type: string, data: Record<string, unknown>) {
  try {
    const res = await fetch(SUPABASE_URL + "/functions/v1/send-email", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: "Bearer " + SUPABASE_KEY },
      body: JSON.stringify({ type, data }),
    });
    if (!res.ok) console.error("BILLING_EMAIL_ERR type=" + type + " status=" + res.status);
    return res.ok;
  } catch (e) {
    console.error("BILLING_EMAIL_ERR type=" + type + ": " + (e instanceof Error ? e.message : String(e)));
    return false;
  }
}

async function audit(businessId: string, action: string, before: unknown, after: unknown, metadata: unknown) {
  await supabase.from("audit_logs").insert({
    actor_id: null,
    business_id: businessId,
    action_type: action,
    target_entity: "businesses",
    target_id: businessId,
    before_state: before,
    after_state: after,
    metadata,
    source: "billing-enforcement",
  });
}

Deno.serve(async (req: Request) => {
  if (req.method !== "POST") return new Response("Not allowed", { status: 405 });

  // This function changes tenant trading state, so it must never be publicly
  // triggerable. verify_jwt is false at the gateway (the service-role key is
  // sb_secret_*, not a JWT, so the gateway would 401 it), which means auth is
  // this function's own job.
  //
  // Two accepted callers, so no new secret has to be provisioned before this
  // can run: the x-billing-key shared secret (kb-sync pattern), or a
  // service-role bearer. Unauthenticated is always rejected — unlike kb-sync,
  // which silently allows everything when its key env is unset.
  const billingKey = req.headers.get("x-billing-key") || "";
  const bearer = (req.headers.get("authorization") || "").replace(/^Bearer\s+/i, "").trim();
  const authorised = (ENFORCEMENT_KEY && billingKey === ENFORCEMENT_KEY) || (!!SUPABASE_KEY && bearer === SUPABASE_KEY);
  if (!authorised) {
    return new Response(JSON.stringify({ ok: false, error: "Unauthorized" }), { status: 401, headers: JSON_HEADERS });
  }

  try {
    // Every issued-but-unpaid invoice. DRAFT is not yet owed; PAID and
    // PAID_MANUALLY are settled.
    const { data: invoices, error } = await supabase
      .from("platform_invoices")
      .select("id, business_id, invoice_number, amount_zar, period_start, period_end, plan_name, sent_at, yoco_payment_link_url, email_overage_count, email_overage_zar, pro_rated, pause_note")
      .eq("status", "SENT")
      .not("sent_at", "is", null)
      .order("sent_at", { ascending: true });

    if (error) {
      console.error("BILLING_ENFORCEMENT_QUERY_ERR: " + error.message);
      return new Response(JSON.stringify({ ok: false, error: error.message }), { status: 500, headers: JSON_HEADERS });
    }

    // One decision per tenant, driven by their OLDEST unpaid invoice. A tenant
    // with three overdue invoices is suspended once, not three times.
    const oldestPerBusiness = new Map<string, any>();
    for (const inv of (invoices || []) as any[]) {
      if (!oldestPerBusiness.has(inv.business_id)) oldestPerBusiness.set(inv.business_id, inv);
    }

    const now = Date.now();
    const results = { checked: 0, past_due: 0, suspended: 0, unchanged: 0 };

    for (const [businessId, inv] of oldestPerBusiness) {
      results.checked++;

      const { data: biz } = await supabase.from("businesses")
        .select("business_name, subscription_status, suspension_reason, billing_admin_user_id")
        .eq("id", businessId).maybeSingle();
      if (!biz) { results.unchanged++; continue; }

      const status = String(biz.subscription_status || "").toUpperCase();
      const daysOverdue = Math.floor((now - new Date(inv.sent_at).getTime()) / 86_400_000);

      // Suspend: past the suspend threshold and not already suspended.
      if (daysOverdue >= SUSPEND_DAYS && status !== "SUSPENDED") {
        const { error: updErr } = await supabase.from("businesses")
          .update({ subscription_status: "SUSPENDED", suspension_reason: "NON_PAYMENT" })
          .eq("id", businessId);
        if (updErr) { console.error("BILLING_SUSPEND_ERR business=" + businessId + " err=" + updErr.message); continue; }

        await audit(businessId, "BILLING_SUSPENDED",
          { subscription_status: status, suspension_reason: biz.suspension_reason ?? null },
          { subscription_status: "SUSPENDED", suspension_reason: "NON_PAYMENT" },
          { invoice_number: inv.invoice_number, days_overdue: daysOverdue, threshold_days: SUSPEND_DAYS });

        const contact = await billingContact(businessId, biz.billing_admin_user_id);
        if (contact) {
          await sendEmail("PLATFORM_INVOICE_OUTSTANDING", {
            email: contact.email, name: contact.name,
            business_name: biz.business_name || "",
            platform_invoice_number: inv.invoice_number,
            period_start: inv.period_start, period_end: inv.period_end,
            plan_name: inv.plan_name, amount_zar: inv.amount_zar,
            email_overage_count: inv.email_overage_count, email_overage_zar: inv.email_overage_zar,
            pro_rated: inv.pro_rated, pause_note: inv.pause_note,
            yoco_payment_link_url: inv.yoco_payment_link_url,
          });
        } else {
          console.warn("BILLING_NO_CONTACT business=" + businessId);
        }

        // OPERATOR_ALERT is the existing internal-alert type (heading + intro).
        // Inventing a new type here would 400 silently in send-email, which is
        // how the partnership-invite emails went missing for weeks.
        if (PLATFORM_ALERT_EMAIL) {
          await sendEmail("OPERATOR_ALERT", {
            business_id: businessId,
            email: PLATFORM_ALERT_EMAIL,
            heading: "Tenant suspended for non-payment",
            ref: inv.invoice_number,
            intro: (biz.business_name || businessId) + " has been suspended. Invoice " + inv.invoice_number +
              " is " + daysOverdue + " days overdue (threshold " + SUSPEND_DAYS + " days). Amount: R" + inv.amount_zar + ".",
          });
        }

        console.log("BILLING_SUSPENDED business=" + businessId + " days=" + daysOverdue + " invoice=" + inv.invoice_number);
        results.suspended++;
        continue;
      }

      // Warn: past the grace threshold and still in a normal trading state.
      // PAST_DUE itself is excluded, which is what makes a same-day re-run a
      // no-op instead of a second email.
      if (daysOverdue >= GRACE_DAYS && (status === "ACTIVE" || status === "TRIAL")) {
        const { error: updErr } = await supabase.from("businesses")
          .update({ subscription_status: "PAST_DUE" })
          .eq("id", businessId);
        if (updErr) { console.error("BILLING_PAST_DUE_ERR business=" + businessId + " err=" + updErr.message); continue; }

        await audit(businessId, "BILLING_PAST_DUE",
          { subscription_status: status },
          { subscription_status: "PAST_DUE" },
          { invoice_number: inv.invoice_number, days_overdue: daysOverdue, threshold_days: GRACE_DAYS });

        const contact = await billingContact(businessId, biz.billing_admin_user_id);
        if (contact) {
          await sendEmail("PLATFORM_INVOICE_OUTSTANDING", {
            email: contact.email, name: contact.name,
            business_name: biz.business_name || "",
            platform_invoice_number: inv.invoice_number,
            period_start: inv.period_start, period_end: inv.period_end,
            plan_name: inv.plan_name, amount_zar: inv.amount_zar,
            email_overage_count: inv.email_overage_count, email_overage_zar: inv.email_overage_zar,
            pro_rated: inv.pro_rated, pause_note: inv.pause_note,
            yoco_payment_link_url: inv.yoco_payment_link_url,
          });
        } else {
          console.warn("BILLING_NO_CONTACT business=" + businessId);
        }

        console.log("BILLING_PAST_DUE business=" + businessId + " days=" + daysOverdue + " invoice=" + inv.invoice_number);
        results.past_due++;
        continue;
      }

      results.unchanged++;
    }

    return new Response(JSON.stringify({ ok: true, ...results, grace_days: GRACE_DAYS, suspend_days: SUSPEND_DAYS }), {
      status: 200, headers: JSON_HEADERS,
    });
  } catch (err) {
    console.error("BILLING_ENFORCEMENT_ERR:", err);
    return new Response(JSON.stringify({ ok: false, error: err instanceof Error ? err.message : String(err) }), {
      status: 500, headers: JSON_HEADERS,
    });
  }
});
